# Generated by Django 3.2.13 on 2022-10-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='C_pluseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='CModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='CsharpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='ElixirModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='GoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='JavaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='JavascriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='PythonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='ReactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='RubyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
        migrations.CreateModel(
            name='RubyrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('videos', models.FileField(upload_to='Sapaklar_videos')),
            ],
        ),
    ]
