# Generated by Django 3.2.13 on 2022-10-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElixirModel',
            new_name='CssModel',
        ),
        migrations.RenameModel(
            old_name='AngularModel',
            new_name='HtmlModel',
        ),
    ]
