# Generated by Django 3.2.13 on 2022-10-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20221026_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RubyrailModel',
            new_name='FlutterModel',
        ),
    ]
