# Generated by Django 3.2.13 on 2022-11-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_rubyrailmodel_fluttermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_plusemodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='c_plusemodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='c_plusemodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='c_plusemodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='cmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='cmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='csharpmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='csharpmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='csharpmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='csharpmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='cssmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cssmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cssmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='cssmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='djangomodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='djangomodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='djangomodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='djangomodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='fluttermodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fluttermodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fluttermodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='fluttermodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='gomodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gomodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gomodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='gomodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='htmlmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='htmlmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='htmlmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='htmlmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='javamodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javamodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javamodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='javamodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='javascriptmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javascriptmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javascriptmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='javascriptmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='pythonmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pythonmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pythonmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='pythonmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='reactmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reactmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reactmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='reactmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='rubymodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rubymodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rubymodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
        migrations.AddField(
            model_name='rubymodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Sapaklar_videos'),
        ),
    ]
