# Generated by Django 3.2.13 on 2022-10-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AngularProjectModel',
            new_name='CssProjectModel',
        ),
        migrations.RenameModel(
            old_name='ElixirProjectModel',
            new_name='HtmlProjectModel',
        ),
    ]
