# Generated by Django 3.2.13 on 2022-11-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_rename_rubyrailprojectmodel_flutterprojectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_pluseprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='c_pluseprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='c_pluseprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='c_pluseprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='cprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='cprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='csharpprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='csharpprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='csharpprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='csharpprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='cssprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cssprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cssprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='cssprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='djangoprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='djangoprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='djangoprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='djangoprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='flutterprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flutterprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flutterprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='flutterprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='goprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='goprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='goprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='goprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='htmlprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='htmlprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='htmlprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='htmlprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='javaprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javaprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javaprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='javaprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='javascriptprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javascriptprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='javascriptprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='javascriptprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='nodeprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nodeprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nodeprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='nodeprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='pythonprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pythonprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pythonprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='pythonprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='reactprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reactprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reactprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='reactprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='rubyprojectmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rubyprojectmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rubyprojectmodel',
            name='videos_en',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
        migrations.AddField(
            model_name='rubyprojectmodel',
            name='videos_ru',
            field=models.FileField(null=True, upload_to='Project_videos'),
        ),
    ]
